name: Hello world first workflow

on:
 push:
  paths: 
#      - "'**'"
     - "'hello_world.yaml'"
 workflow_dispatch:

jobs:
  hello:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: hello world
         run: echo "hellow world Praveen!"
         shell: bash
  bye:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bye
        run: echo "Bye Praveen!"
        shell: bash
